[profile.default]
src = 'contracts'
out = 'out'
libs = ['../../node_modules','node_modules','lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read-write", path = "./"}]
